/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 beach_chair.gltf --transform
Author: Tahir.Muhamad.Ajmal. (https://sketchfab.com/Tahir.Muhamad.Ajmal.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beach-chair-2873b42fd98d4e879bfd3d29cf72a9af
Title: beach chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function BeachChair(props) {
  const { nodes, materials } = useGLTF("/beach_chair-transformed.glb");
  return (
    <group
      position={[-1.5, 2, 0.4]}
      rotation={[1.8, -0.4, 0.1]}
      scale={0.8}
      {...props}
      dispose={null}
    >
      <group position={[-0.71, 1.68, -0.46]} rotation={[-0.24, 0, 0]}>
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Pine_Wood}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Pine_Wood}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Material}
        position={[0, 0.03, 0]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Pine_Wood}
        position={[-0.71, -0.1, -0.02]}
        rotation={[-0.24, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Material}
        position={[-0.71, 1.13, -0.32]}
        rotation={[-0.24, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials["Material.001"]}
        position={[-0.71, 1.68, -0.46]}
        rotation={[-0.24, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/beach_chair-transformed.glb");
