/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 malibu.gltf --transform
Author: Jester (https://sketchfab.com/jesterAlp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/malibu-sunset-5960dfd9ef1140539e0041f44090f562
Title: Malibu sunset
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Malibu(props) {
  const { nodes, materials } = useGLTF("/malibu-transformed.glb");
  return (
    <group
      scale={0.2}
      position={[1.0, 2.6, 0.75]}
      rotation={[Math.PI / 2, 0, 0]}
      {...props}
      dispose={null}
    >
      <group scale={0.01}>
        <mesh
          geometry={nodes.Glas_Glas_MTL_0.geometry}
          material={materials.Glas_MTL}
          position={[0, 0, -0.81]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.drink_Drink_MTL_0.geometry}
          material={materials.Drink_MTL}
          position={[0, 2.9, -1.07]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.93}
        />
        <mesh
          geometry={nodes.orange_Deco_MSL_0.geometry}
          material={materials.Deco_MSL}
          position={[0, 135.7, 35.3]}
          rotation={[Math.PI, 1.38, -3.03]}
        />
        <mesh
          geometry={nodes.lime_Deco_MSL_0.geometry}
          material={materials.Deco_MSL}
          position={[-16.95, 135.73, 30.58]}
          rotation={[0, 1.26, 0.47]}
          scale={1.25}
        />
        <mesh
          geometry={nodes.cherry1_Deco_MSL_0.geometry}
          material={materials.Deco_MSL}
          position={[0, 142, -27.58]}
          rotation={[-0.25, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.cherry2_Deco_MSL_0.geometry}
          material={materials.Deco_MSL}
          position={[-16.97, 139.08, -15.04]}
          rotation={[-2.28, 0.48, -3.11]}
        />
        <mesh
          geometry={nodes.ice_Ice_MTL_0.geometry}
          material={materials.Ice_MTL}
          position={[2.68, 97.85, 10]}
          rotation={[-1.05, 0.39, -0.22]}
        />
        <mesh
          geometry={nodes.straw_Deco_MSL_0.geometry}
          material={materials.Deco_MSL}
          position={[18.96, 22.88, 6.14]}
          rotation={[-1.6, -0.42, -0.14]}
        />
        <mesh
          geometry={nodes.Cone001_Deco_MSL_0.geometry}
          material={materials.Deco_MSL}
          position={[-25.16, 151.9, -34.51]}
          rotation={[-2.11, -0.51, 0.85]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/malibu-transformed.glb");
