/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 palm_tree.gltf --transform
Author: aliyeredon (https://sketchfab.com/aliyeredon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-palm-tree-model-vol1-24bc514ac5e04e56a97fcb9b555aa67d
Title: Realistic Palm Tree Model vol.1
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function PalmTree(props) {
  const { nodes, materials } = useGLTF("/palm_tree-transformed.glb");
  return (
    <group
      scale={0.24}
      rotation={[Math.PI / 2, 0, 0]}
      {...props}
      dispose={null}
    >
      <group scale={0.01}>
        <mesh
          geometry={nodes.Palm_1_1_Palm_Center_0.geometry}
          material={materials.Palm_Center}
        />
        <mesh
          geometry={nodes.Palm_1_1_Palm_Trunk_0.geometry}
          material={materials.Palm_Center}
        />
        <mesh
          geometry={nodes.Palm_1_1_Palm_Leaf_0.geometry}
          material={materials.Palm_Leaf}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/palm_tree-transformed.glb");
