/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 pineapple.gltf --transform
Author: Franco Pizzani (https://sketchfab.com/LittleNinja)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pineapple-scan-1c77bd376c0940cab3ec72b037a6fc46
Title: Pineapple Scan
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function PineApple(props) {
  const { nodes, materials } = useGLTF("/pineapple-transformed.glb");
  return (
    <group scale={0.02} position={[1.5, 2.2, 0.75]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
          position={[-6.06, -6.3, -0.96]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pineapple-transformed.glb");
