/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 sketch.gltf --transform
*/

import { Center } from "@react-three/drei";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Model(props) {
  const { nodes, materials } = useGLTF("/sketch-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.brush_Petal_g0_b0.geometry}
        material={materials.brush_Petal}
      />
      <mesh
        geometry={nodes.brush_Petal_g0_b1.geometry}
        material={materials.brush_Petal}
      />
      <mesh
        geometry={nodes.brush_Petal_g0_b2.geometry}
        material={materials.brush_Petal}
      />
      <mesh
        geometry={nodes.brush_Petal_g0_b3.geometry}
        material={materials.brush_Petal}
      />
    </group>
  );
}

function GrassSegment() {
  return (
    <group rotation={[1.55, 0.25, 0.0]}>
      <group position={[-0.6, 0, -0.2]}>
        <Model />
      </group>
      <group>
        <Model />
      </group>
      <group position={[0.5, 0, 0.15]}>
        <Model />
      </group>
      <group position={[1, 0, 0.25]}>
        <Model />
      </group>
      <group position={[1, 0, 0.25]}>
        <Model />
      </group>
    </group>
  );
}

export default function GrassWall() {
  return (
    <Center>
      <group scale={[3, 2, 3]} rotation={[0, 0, 0.0]}>
        <group position={[0, 1.6, 0]}>
          <GrassSegment />
        </group>
        <group>
          <GrassSegment />
        </group>
        <group position={[0, 0.8, 0]}>
          <GrassSegment />
        </group>
        <group position={[0, -0.8, 0]}>
          <GrassSegment />
        </group>
        <group position={[0, -1.6, 0]}>
          <GrassSegment />
        </group>
        <group position={[0, -2.3, 0]}>
          <GrassSegment />
        </group>
      </group>
    </Center>
  );
}

useGLTF.preload("/sketch-transformed.glb");
