/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 outside_table.gltf --transform
Author: RobErtArt (https://sketchfab.com/RobErtArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/outside-table-ba3a53a73b3f409ea1f2898077e517cf
Title: Outside Table
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Table(props) {
  const { nodes, materials } = useGLTF("/outside_table-transformed.glb");
  return (
    <group
      position={[Math.PI / 2, 2.4, 0.2]}
      rotation={[Math.PI / 2, 1, 0]}
      scale={0.4}
      {...props}
      dispose={null}
    >
      <group scale={0.01}>
        <mesh
          geometry={nodes.Cube_oakdark_0.geometry}
          material={materials.oakdark}
          position={[0, 108, -102.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube003_oakdark_0.geometry}
          material={materials.oakdark}
          position={[0, 102, -3.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube004_oakdark_0.geometry}
          material={materials.oakdark}
          position={[0, 102, -203.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube005_oakdark_0.geometry}
          material={materials.oakdark}
          position={[0, 50, -103.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube006_oakdark_0.geometry}
          material={materials.oakdark}
          position={[0, 102, -103.62]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube007_oakdark_0.geometry}
          material={materials.oakdark}
          position={[0, 49.58, 4.8]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube008_oakdark_0.geometry}
          material={materials.oakdark}
          position={[0, 49.58, -211.19]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube001_oakdark_0.geometry}
          material={materials.oakdark}
          position={[44, 108, -102.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube002_oakdark_0.geometry}
          material={materials.oakdark}
          position={[-44.15, 108, -102.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane001_oakdark_0.geometry}
          material={materials.oakdark}
          position={[-20.61, 80.36, -3.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane002_oakdark_0.geometry}
          material={materials.oakdark}
          position={[-20.61, 80.36, -203.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/outside_table-transformed.glb");
