/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 tikiTotem.gltf --transform
Author: Dav1d- (https://sketchfab.com/Dav1d-)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tiki-totem-b119531299e14d6db28090424a004052
Title: Tiki Totem
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function TikiTotem(props) {
  const { nodes, materials } = useGLTF("/tikiTotem-transformed.glb");
  return (
    <group scale={0.1} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={
            nodes["CL_UMesh_PM3D_Plane3D7_SeamsColor_Material_#48_0"].geometry
          }
          material={materials.Material_48}
        />
        <mesh
          geometry={
            nodes["CL_UMesh_PM3D_Plane3D7_SeamsColor_Material_#48_0_1"].geometry
          }
          material={materials.Material_48}
        />
        <mesh
          geometry={
            nodes["CL_UMesh_PM3D_Plane3D7_SeamsColor_Material_#48_0_2"].geometry
          }
          material={materials.Material_48}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/tikiTotem-transformed.glb");
